# Generated by Django 2.2.5 on 2020-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(db_index=True)),
                ('truth', models.CharField(max_length=20)),
                ('cube', models.CharField(max_length=20)),
                ('google', models.CharField(max_length=255)),
                ('google_spam', models.FloatField()),
                ('google_not_spam', models.FloatField()),
                ('ibm', models.CharField(max_length=255)),
                ('ibm_spam', models.FloatField()),
                ('ibm_not_spam', models.FloatField()),
            ],
            options={
                'db_table': 'message_data',
            },
        ),
    ]
